
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
spring:
  application:
    name: auth-server
security:
  oauth2:
    client:
      client-id: web
      client-secret: web_secret
  user:
    password: user
logging:
  level:
    org.springframework.security: DEBUG